#general:
#z_dim: 3
z_dim: 4
generator_type: classical_normal
stage: train
experiment_name: GaussGAN-manual
killer: false  

quantum_qubits: 6
quantum_layers: 2
quantum_basis: 3
quantum_shots: 100

#training:
#grad_penalty: 2
grad_penalty: 0.2
n_critic: 5
n_predictor: 5
checkpoint_path: "checkpoints/"
agg_method: prod
max_epochs: 50
batch_size: 256
learning_rate: 0.001

nn_gen: "[256,256]" 
#nn_disc: "[32,128]"  
nn_disc: "[256,256]"   
nn_validator: "[128,128]"   
non_linearity: "LeakyReLU" # LeakyReLU or ReLU

std_scale: 1.1
min_std: 0.5

#data:
dataset_type: "NORMAL"

#metrics:
metrics: ['IsPositive', 'LogLikelihood', 'KLDivergence', 'WassersteinDistance', 'MMDDistance', 'MMDivergence']

wasserstein_aggregation: "mean"
mmd_kernel: "rbf"
mmd_gamma: 1.0
mmd_bandwidths: [0.1, 1.0, 10.0]
mmd_target_samples: 1000

convergence_patience: 10
convergence_min_delta: 0.0001
convergence_monitor: "KLDivergence"
convergence_window: 5

stability_analysis: true
stability_runs: 5
stability_metrics: ['KLDivergence', 'WassersteinDistance', 'MMDDistance']


#misc:
accelerator: gpu
validation_samples: 500
seed: 41

rl_weight: 100