[tool:pytest]
# PyTest configuration for GaussGAN testing

# Test discovery
testpaths = docs/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Minimum version
minversion = 7.0

# Add options
addopts = 
    --strict-markers
    --strict-config
    --verbose
    --tb=short
    --showlocals
    --durations=10
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-report=xml:coverage.xml
    --cov-branch
    --cov-fail-under=80

# Coverage configuration  
[coverage:run]
source = source
omit = 
    */tests/*
    */test_*
    */__pycache__/*
    */venv/*
    */env/*
    setup.py
    */migrations/*

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    if self.debug:
    if settings.DEBUG
    raise AssertionError
    raise NotImplementedError
    if 0:
    if __name__ == .__main__.:
    pass

# Test markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    quantum: marks tests requiring quantum backends
    gpu: marks tests requiring GPU
    integration: marks integration tests
    performance: marks performance benchmark tests
    statistical: marks statistical validation tests
    regression: marks regression tests
    unit: marks unit tests
    e2e: marks end-to-end tests
    
# Warnings configuration
filterwarnings =
    ignore::UserWarning
    ignore::PendingDeprecationWarning
    ignore::DeprecationWarning:pennylane.*
    ignore::DeprecationWarning:torch.*
    error::RuntimeWarning
    
# Timeout for tests (in seconds)
timeout = 300
timeout_method = thread

# Parallel execution
# Use with: pytest -n auto
# Requires: pip install pytest-xdist

# Log configuration
log_cli = false
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(name)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Benchmark configuration (for pytest-benchmark)
[tool:pytest_benchmark]
min_rounds = 3
max_time = 30
warmup = true
warmup_iterations = 2
sort = mean
columns = min, max, mean, stddev, median, iqr, outliers, ops, rounds, iterations